package helpers

const (
	LogKeyError          = "error"
	LogKeyDuration       = "duration"
	LogKeyMethod         = "method"
	LogKeyPath           = "path"
	LogKeyStatusCode     = "status_code"
	LogKeyAlias          = "alias"
	LogKeyVersion        = "version"
	LogKeyFilename       = "filename"
	LogKeySource         = "source"
	LogKeyRepoURL        = "repo_url"
	LogKeyDescription    = "description"
	LogKeyLimit          = "limit"
	LogKeyOffset         = "offset"
	LogKeyTotal          = "total"
	LogKeySourceURL      = "source_url"
	LogKeyVersionsCount  = "versions_count"
	LogKeyRequestURL     = "request_url"
	LogKeyEncryptionType = "encryption_type"
	LogKeyAuthProvider   = "auth_provider"
	LogKeyTokenMasked    = "token_masked"
	LogKeyAction         = "action"
)

const (
	ActionGetAggregateManifest  = "get_aggregate_manifest"
	ActionGetCatalogVersion     = "get_catalog_version"
	ActionGetManifest           = "get_manifest"
	ActionGetManifestData       = "get_manifest_data"
	ActionGetManifestAggregated = "get_manifest_aggregated"
	ActionGetFile               = "get_file"
	ActionGetVersions           = "get_versions"
	ActionCreateProject         = "create_project"
	ActionGetProject            = "get_project"
	ActionUpdateProject         = "update_project"
	ActionDeleteProject         = "delete_project"
	ActionListProjects          = "list_projects"
	ActionResolveProject        = "resolve_project"
)
